### ISSUE TITLE
一个建议

### ISSUE THREAD

**Issue by xutaiping** [AnliaLee/BookPage#1]
真实书本翻页的时候，是可以把当前页翻到屏幕左边去的，就是说 a 这个点的 x 值可以为负，最小可以为-viewWidth，不知道大牛有空能不能考虑改进一下。谢谢。

**Comment by AnliaLee** [comment]
目前手机上大多数阅读类App都只是单页翻页，你说的这种双页的翻页效果可能在平板上比较多见吧。其实你想实现那样的效果把相应的限制去掉就可以了呀，我代码注释应该挺全的...

**Comment by xutaiping** [comment]
您好，问题我自己解决了。不过这个功能并不是双页翻页才需要。
单页翻页的时候，如果a.x值不能为负的话，会导致从右往左翻页的时候动画进行到屏幕的一半就完成（书页翻了一半），此时a.x值为0。
放开a.x的限制，可以让书页翻到屏幕左边，这时候当前屏幕可以有书页慢慢滑出屏幕的效果，而不是滑到一半突然全部消失。
